spring:
  datasource:
    url: jdbc:mysql://${env.MYSQL_HOST}:${env.MYSQL_PORT}/${env.MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${env.MYSQL_USER}
    password: ${env.MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false

---
# 개발 (dev) 프로파일
spring:
  config:
    activate:
      on-profile: dev

---
# 운영 (prod) 프로파일
spring:
  config:
    activate:
      on-profile: prod
