spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

---
# 개발 (dev) 프로파일
spring:
  config:
    activate:
      on-profile: dev

---
# 운영 (prod) 프로파일
spring:
  config:
    activate:
      on-profile: prod
